# Generated by Django 4.1.7 on 2023-11-17 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_image_id', models.CharField(max_length=100)),
                ('action_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_heading', models.CharField(max_length=255)),
                ('activity_image_id', models.CharField(max_length=100)),
                ('activity_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audio_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('audio_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_type', models.CharField(max_length=255)),
                ('book_image_id', models.CharField(max_length=100)),
                ('book_copy_writing', models.TextField()),
                ('book_heading', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_image_id', models.CharField(max_length=100)),
                ('emotion_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('food_image_id', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=100)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('information_id', models.AutoField(primary_key=True, serialize=False)),
                ('information_heading', models.CharField(max_length=255)),
                ('information_image_id', models.CharField(max_length=100)),
                ('information_copy_writing', models.TextField()),
                ('information_date', models.DateField()),
                ('information_source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('meditation_id', models.AutoField(primary_key=True, serialize=False)),
                ('meditation_name', models.CharField(max_length=100)),
                ('meditation_image_id', models.CharField(max_length=100)),
                ('play', models.IntegerField()),
                ('audio_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShareLoop',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_emotion', models.CharField(max_length=255)),
                ('shareLoop_copy_writing', models.TextField()),
                ('image_list_id', models.CharField(max_length=100)),
                ('release_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_avatar_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('iphone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_text', models.TextField()),
                ('release_time', models.DateTimeField()),
                ('action_list', models.ManyToManyField(to='mental_app.action')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_app.user')),
            ],
        ),
    ]
