# Generated by Django 4.1.7 on 2023-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio_data',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(default=0, upload_to='audio/'),
            preserve_default=False,
        ),
    ]
