# Generated by Django 4.1.7 on 2023-11-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0003_remove_shareloop_image_list_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareloop',
            old_name='user_id',
            new_name='shereloop_id',
        ),
        migrations.AddField(
            model_name='shareloop',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
