# Generated by Django 4.1.7 on 2023-11-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0005_rename_shereloop_id_shareloop_shareloop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareloop',
            old_name='shareLoop_copy_writing',
            new_name='shareLoop_copy_writing',
        ),
    ]
