# Generated by Django 4.1.7 on 2023-11-22 08:47

from django.db import migrations, models
import mental_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0007_meditation_meditation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionrecord',
            name='action_list',
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='action_list',
            field=models.TextField(default=1, verbose_name=mental_app.models.Action),
            preserve_default=False,
        ),
    ]
