# Generated by Django 4.1.7 on 2023-11-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0008_remove_emotionrecord_action_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionrecord',
            name='action_list',
            field=models.TextField(),
        ),
    ]
