# Generated by Django 4.1.7 on 2023-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0009_alter_emotionrecord_action_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionrecord',
            name='action_list',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='emotion_text',
            field=models.TextField(max_length=2),
        ),
    ]
