# Generated by Django 4.1.7 on 2023-11-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0010_alter_emotionrecord_action_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_image_id', models.CharField(max_length=100)),
                ('test_question', models.CharField(max_length=100)),
                ('test_choiceA', models.CharField(max_length=50)),
                ('test_choiceB', models.CharField(max_length=50)),
                ('test_choiceC', models.CharField(max_length=50)),
            ],
        ),
    ]
