# Generated by Django 4.1.7 on 2023-12-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0011_testmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
