# Generated by Django 4.1.7 on 2023-12-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0012_audio_audio_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio_file',
        ),
    ]
