# Generated by Django 4.1.7 on 2023-12-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_app', '0013_remove_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_avatar_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
